language: ruby
rvm:
- 3.0
node_js:
- 15
services:
- postgresql
- redis
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
before_install:
# RUBYGEMS
- gem update --system
- gem install bundler
# NODE
- nvm install v15.12.0
install: bundle install --jobs=3 --retry=3
before_script:
# POSTGRESQL
- createuser flyweight
- createdb -O flyweight flyweight_test
# NODE
- nvm use
- npm i -g yarn
- yarn install
# SEED
- bundle exec rails db:migrate
# MANIFEST
- RAILS_ENV=test bundle exec rails webpacker:compile
env:
  global:
  - RAILS_TEST_DB_USERNAME=travis
  - PGUSER=travis
  - PGPORT=5433
  - PATH="$HOME/bin:$PATH"
script:
- rspec spec
