default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: flyweight

development:
  <<: *default
  database: flyweight_development

test: &test
  <<: *default
  database: flyweight_test
  owner: flyweight
  username: <%= ENV.fetch('RAILS_TEST_DB_USERNAME') { 'tmorgan' } %>
  port: <%= ENV.fetch('PGPORT') { 5432 } %>

cypress: *test

production:
  <<: *default
  database: flyweight_production
