# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.5
        env:
          POSTGRES_DB: avfacts_test
          POSTGRES_USER: avfacts
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"
      - name: Install Node.js dependencies
        run: yarn install
      - name: Create test database
        env:
          POSTGRES_DB: flyweight_test
          POSTGRES_USER: flyweight
          POSTGRES_PASSWORD: postgres
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          sudo apt-get install libpq-dev
          RAILS_ENV=test bin/rails db:setup
      - name: Run unit tests
        env:
          POSTGRES_DB: flyweight_test
          POSTGRES_USER: flyweight
          POSTGRES_PASSWORD: postgres
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bundle exec rspec spec

  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"
      - name: Install Node.js dependencies
        run: yarn install
      - name: Run Rubocop
        run: |
          gem install rubocop-rails rubocop-rspec rubocop-performance
          git clone https://gist.github.com/65e21b9e8b0d1db285dcb4fc627b98fa.git .rubocop
          cp .rubocop/.rubocop.yml .
          rubocop --parallel
      - name: Run Brakeman
        run: |
          #gem install brakeman
          git clone https://github.com/presidentbeef/brakeman.git
          pushd brakeman
          gem build brakeman.gemspec
          gem install brakeman*.gem
          popd
          brakeman -q -w2
